version: '3'

services:
  thing-service-postgres-testing:
    container_name: thing-service-postgres-testing
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=things
