name: Lint and Test

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  unit-tests:
    uses: darrylmorton/ct-continuous-workflows/.github/workflows/nodejs-test-unit.yml@v1
    with:
      nodejs-version: '22.x'

  integration-tests:
    uses: darrylmorton/ct-continuous-workflows/.github/workflows/nodejs-test-integration.yml@v1
    with:
      nodejs-version: '22.x'
      db-migrate-flag: true
